### ISSUE TITLE
Doesn't support Environment Variable PORT

### ISSUE THREAD

**Issue by drusellers** [qiuxiafei/zk-web#13]
Trying to use zk-web with foreman but doesn't support changing the port number based on environment variable.

**Comment by qiuxiafei** [comment]
why not edit the config file?

**Comment by drusellers** [comment]
Short Answer: http://12factor.net/
:)

Also, [foreman](http://ddollar.github.io/foreman/) will pass a PORT environment variable to be used and it would be nice to be able to use foreman. Foreman, will also spit out upstart files, systemd files which makes running my tools much easier. I'm happy to contribute a change that will allow both the config file and the env var.

**Comment by qiuxiafei** [comment]
it would be nice if u can contribute.

**Comment by drusellers** [comment]
Ok, cool beans. Are you ok if I pull in the environ package? https://github.com/weavejester/environ

**Comment by qiuxiafei** [comment]
If it can be achieved by simply wrap `System.getEnv()`, don't introduce unnecessary external library.^_^
