### ISSUE TITLE
'Feature' request: unit tests ans CI

### ISSUE THREAD

**Issue by Sh4pe** [qiuxiafei/zk-web#21]
This project is missing unit tests and continuous integration.

I'd propose to use [Midje](https://github.com/marick/Midje) for unit testing and to use [Travis CI](https://travis-ci.org) for continuous integration.

If you don't mind my proposal I would volunteer to implement these.

**Comment by qiuxiafei** [comment]
very welcome!

**Comment by Sh4pe** [comment]
I will not have the time to do this. Hence I close this issue.
